### ISSUE TITLE
Error with Collection ID variable in IOS SWIFT

### ISSUE THREAD

**Issue by FahdSaif** [hypertrack/live-app-ios#10]
Hi,

I am working on Hypertrack for the first time. I am getting this error in IOS SWIFT.

`018/07/06 13:36:50:217[ios_sdk][0.7.0][] [] [82208] [ERROR] [HTApiRouter:336]getHTError - Error while https://api.hypertrack.com/api/v2/actions/track/?collection_id= : ["In track API atleast one of id or unique_id or collection_id or short_code must be provided"]`

What should I provide to this variable?

`fileprivate let collectionIdKey = ??`

I tried 
`fileprivate let collectionIdKey=UUID().uuidString`

and my API key also, it didnt work..Please assist.

**Comment by aasawa99** [comment]
Its a track action api, so first create the action with unique collectionId, and later you can use the same collectionId to track.
https://docs.hypertrack.com/sdks/ios/actions.html

**Comment by tulushev** [comment]
Updated to the new version
