### ISSUE TITLE
Type 'HyperTrack' has no member 'createAction'

### ISSUE THREAD

**Issue by bhanu501** [hypertrack/live-app-ios#12]
Getting this error. while creating action

![createaction](https://user-images.githubusercontent.com/35935819/44012948-43778e20-9ee0-11e8-9c20-de25addd790e.png)

**Comment by amanwar** [comment]
@bhanu501 Please use the latest version (0.7.25) of HyperTrack SDK to resolve this issue.

**Comment by tulushev** [comment]
Updated to the new version
